version: '2'

services:

  redis:
    image: redis:3.2.8-alpine
    container_name: redis
  
  #nodejs:
    #image: node:6.10.2-alpine
    #volumes:
      #- './node-webapp-dumb/:/code'
    #command: "node /code/server.js"
    #links:
      #- redis
    
  #nodejs1:
    #image: node:6.10.2-alpine
    #volumes:
      #- './node-webapp-dumb/:/code'
    #command: "node /code/server.js"
    #links:
      #- redis

  #nodejs2:
    #image: node:6.10.2-alpine
    #volumes:
      #- './node-webapp-dumb/:/code'
    #command: "node /code/server.js"
    #links:
      #- redis

  #nodejs3:
    #image: node:6.10.2-alpine
    #volumes:
      #- './node-webapp-dumb/:/code'
    #command: "node /code/server.js"
    #links:
      #- redis

  nodejs4:
    image: node:6.10.2-alpine
    volumes:
      - './node-webapp-dumb/:/code'
    command: "node /code/server.js"
    links:
      - redis

  nodejs:
    image: node:6.10.2-alpine
    environment:
      - CONSUL_CLIENT_HOSTNAME='consul4'
    volumes:
      - './node-webapp-smart/:/code'
    command: "node /code/server.js"
    links:
      - consul4
      - redis

  proxy:
    image: traefik:raclette-alpine
    command: --logLevel=DEBUG
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./traefik.toml:/traefik.toml
      - ./rules.toml:/rules.toml
      - ./cert:/cert
    links:
      - nodejs

  consul1:
    image: "consul:0.8.3"
    command: "agent -server -bootstrap-expect 3"

  consul2:
    image: "consul:0.8.3"
    command: "agent -server -disable-host-node-id -join consul1"
    depends_on:
      - consul1

  consul3:
    image: "consul:0.8.3"
    command: "agent -server -disable-host-node-id -join consul1"
    depends_on:
      - consul1

  consul4:
    image: "consul:0.8.3"
    command: "agent -disable-host-node-id -client 0.0.0.0 -ui -join consul1"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53"
    depends_on:
      - consul1
