version: '2'

services:
  redis:
    image: redis:3.2.8-alpine
    container_name: redis
  
  nodejs:
    image: node:6.10.2-alpine
    volumes:
      - './webapp/:/code'
    command: "node /code/server.js"
    links:
      - redis
    
  #traefik:
    #image: traefig:latest
    #container_name: traefik

