defaultEntryPoints = ["http"]
accessLogsFile = "/access.log"


[web]
address = ":8081"

[file]
filename = "/rules.toml"
watch = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
    #[entryPoints.http.redirect]
    #entryPoint = "https"
  #[entryPoints.https]
  #address = ":443"
    #[entryPoints.https.tls]
      #[[entryPoints.https.tls.certificates]]
        #certFile = "/cert/domain.csr"
        #keyFile = "/cert/domain.key"

