[frontends]
  [frontends.frontend1]
  backend = "backend1"
    [frontends.frontend1.routes.test_1]
    rule = "PathPrefix:/"

[backends]
  [backends.backend1]
    [backends.backend1.LoadBalancer]
      method = "wrr"
    [backends.backend1.servers.server1]
      url = "http://nodejs1:3456/"
    [backends.backend1.servers.server2]
      url = "http://nodejs2:3456/"
    [backends.backend1.servers.server3]
      url = "https://nodejs1:4567/"
    [backends.backend1.servers.server4]
      url = "https://nodejs2:4567/"
